// Dev-only data for scripts/gen-legal.mjs: the plain-English version of the privacy policy and the terms.
// It follows docs/release/legal-site.md section by section (same order, same facts, nothing added) plus the one
// site-only section «This website». Text between [[ ]] is the Arabic label shown in the game; it becomes <bdi lang="ar" dir="rtl">.
// One string per section; gen-legal splits it into sentences (one <p> each).

const NAME = 'Adel Gamal Mohamed Abdullah ([[عادل جمال محمد عبد الله]])'

export const PRIVACY_EN = [
  { h: 'Without signing in', p: 'There is no email, no password and no phone number, no ads, no tracking across apps and no analytics tools other than gameplay statistics. The game connects to our server in four cases: online play; crash reports; a copy of your account that we keep so you can restore it if your phone is wiped or you change it; and asking for the “oldest accepted game version”. That same request also checks whether there is a message from the team or changed game settings, when the home screen opens and every 5 minutes while it is open, with no data from you. It also connects to two outside services: PostHog for statistics and RevenueCat for purchases. The artwork, sounds and fonts are inside the app itself.' },
  { h: 'What stays on your device', p: 'Your name, level, experience, characters, items, settings and gameplay numbers; your running match, if you close the app halfway through; the log of tutorial steps; and a short log of your matches, purchases and app crashes. All of it stays on your device, except what we say below: online play, crash reports, statistics, the account copy and purchases.' },
  { h: 'Account copy', p: 'We keep a copy of your account on our server: your name, your Lahlouh, the characters and cosmetics you bought, attendance, achievements and the list of players you blocked, tied to a random number for your device and a secret kept on your device. It comes with an 8-character recovery code that you type on a new phone to restore your account; the code keeps working for 6 months after you last opened the game. There is no email and no phone number. It is deleted when you press “Delete my account” ([[امسح حسابي]]), or two years after you last used it.' },
  { h: 'Online rooms', p: 'When you play an online match, we send the game server (Colyseus Cloud in Frankfurt) your name, your character, a random number for your device and the room code, together with your moves and actions. Your name and character are shown to everyone in the room, so do not use your real name if you prefer not to. The server passes the rest on only to your friends in the same room. One player’s phone runs the match for everyone, so it knows the players’ cards. The server does not save them in a database, and they are gone when the room closes. And like any server, it sees your internet address (IP address) when you connect. It also counts rooms and messages and measures memory, processor load and uptime so that the service keeps running.' },
  { h: 'Estimation with friends', p: 'When you create a session or join one with a code, we send the same server your name, the profile picture you chose in the game, your level, a random number for your device and your actions in play. Your name and picture are shown to your friends in the session. Each player’s cards go only to that player. The server saves nothing, and everything is gone when the session closes.' },
  { h: 'Crash reports', p: 'Automatic sending is on from the start, and you can turn it off under Settings › Account › “Send crash reports automatically”. When the game crashes it sends a report to our server (Colyseus Cloud in Frankfurt) so that we can fix the fault, at most once every two minutes. It contains your device model, system version, game version, screen size, the latest log events and the error. It contains no name, no room code, no account and no device number. And it goes to no one but the hosting company that runs the server.' },
  { h: 'How a report is kept', p: 'If there is no internet, it waits on your device and is sent later. On the server it is saved in a file that deletes itself after 30 days at most, and we do not store your IP address in it. As for the “Send a problem report” button, you are the one who chooses who receives it.' },
  { h: 'Gameplay statistics', p: 'On iPhone, and on any phone in Europe, the UK and Switzerland, we ask you the first time you open the game and send nothing before you agree. In other countries on Android they are on from the start, after you choose your birth year. You can change your mind at any time under Settings › Account, and if you are under 18 we send nothing. We send numbers about your play without your name or any personal data: the result of each procedure (success or failure, its duration and its score), the end of a match (rank, points and character), character purchases and shop activity, first-use steps, your basic settings (sound, font and frame rate), and device performance while you play.' },
  { h: 'What goes with each number', p: 'A random number for your device (not your name or your account), the game version, the device type, the screen size, your level and the number of your characters. No name, no text you type, no room code, no pictures and no location, and we do not store your IP address.' },
  { h: 'Who receives them', p: 'The numbers go to PostHog (its servers are in Frankfurt, Germany, inside the European Union). It is only a service provider: it stores them for us for one year and then deletes them, and it neither sells them nor uses them for ads. If there is no internet they wait on your device and are sent later. You can turn them off under Settings › Account › “Share gameplay statistics”; they then stop, and we delete what is waiting on your device, together with the device number. If you want us to delete what was already sent, copy your number from the same page and send it to us, and we will delete it within a month.' },
  { h: 'Real-money purchases', p: 'If you buy Lahlouh or “Make your character”, payment is made through the Apple or Google store and we never see your card details. The RevenueCat service confirms the purchase and restores “Make your character” for you if you change your device. It receives the purchase receipt, a random number for the device (not your name) and technical information such as the device type. RevenueCat is a US company and processes this data in the US, for us only. This transfer relies on the contractual clauses approved by the European Union.' },
  { h: 'Motion and microphone', p: 'The home screen and procedures such as “Water balance” and “Spin the safe” use your phone’s tilt and motion only during the attempt, after you agree with the “Go ahead, sir” button. The readings are not recorded and not sent, your location is not used, and touch is always available instead. The “Blow the dust” procedure measures the loudness of your blowing during the attempt, with your permission; nothing is recorded or sent, and tapping is always available instead. In online play only the result of the procedure is sent, not the readings.' },
  { h: 'No chat', p: 'Interaction in a match is through ready-made buttons only (a clap, a kiss, money), and the only thing you type is the room code.' },
  { h: 'Friends', p: 'If you open “Friends”, we keep on the game server your name, your character, your own friend code, your friends list, your requests and room invitations, without your IP address or device model. We delete them if you do not open the game for 180 days, or when you press “Delete my account”.' },
  { h: 'Reports', p: 'When you report a player, we receive their displayed name, their random number and the reason for the report, and we keep them for 90 days. We keep the numbers of banned devices for as long as the ban lasts.' },
  { h: 'Service providers', p: 'We use only three companies. All of them work for us and on our instructions, and are bound to protect your data at the same level as this page or higher. Colyseus Cloud for the game server (Frankfurt), PostHog for statistics (Frankfurt) and RevenueCat for purchases (US). Their privacy policies: cloud-prod.colyseus.io/privacy-policy, posthog.com/privacy and revenuecat.com/privacy.' },
  { h: 'Deleting your account', id: 'delete', p: 'The “Delete my account” button under Settings › Account deletes your account from our server and from your device: everything the game stores on your device, your device’s random number and the recovery code, together with the Lahlouh and the things you bought with it (these do not come back). You can restore “Make your character” with “Restore purchases”. If you clear the app’s data from your phone’s settings, only what is on your device is deleted, and the account copy on the server stays until you delete it. And the statistics that were already sent are deleted if you send us your number, as we said above.' },
  { h: 'What remains after deletion', p: 'We remove your device number from the reports you filed, and the reports stay without a number. We keep the numbers of banned devices, blocked names and the reports filed against the device, to prevent abuse.' },
  { h: 'Your rights', p: 'You have the right to know what we hold about you, to ask us to correct or delete it, and to object or withdraw your consent at any time. Withdrawing your consent does not affect what was done before it. Statistics are by your consent (on iPhone and in Europe, the UK and Switzerland we ask before we start, and they stop if you withdraw); crash reports are so that we can fix the game; online play, purchases and the account copy are so that we can give you what you asked for. Email us at hello@maslahagame.com with the number shown in Settings, and we will reply within a month. If you are in Europe, you have the right to complain to the data protection authority in your country. And if you are in Egypt, you have the right to complain to the Personal Data Protection Centre.' },
  { h: 'Children', p: 'The game is not made for children under 13, and we do not knowingly collect data from them. We ask your birth year and keep only your age band on your device (under 13, under 18 or older), not the year itself. If you are under 18, statistics stay off, and you should ask an adult before you buy anything with real money. If you are under 13, real-money purchases and public rooms are locked. And if you find out that your child sent us data, talk to us and we will delete it.' },
  { h: 'If this changes', p: 'If we add something new that is sent from you, we will change this page before that and write the update date at the top. If the change is big, we will tell you inside the game and ask you again if we need your consent.' },
  { h: 'Contact', p: `The person responsible for your data is ${NAME}, an individual developer in Egypt. For any question or request about your data, email hello@maslahagame.com. The game’s Instagram page, maslaha_game, is for news only, not for data requests.` },
]

export const TERMS_EN = [
  { h: 'About the game', p: `Qaadet Maslaha is an entertainment game by ${NAME}, an individual developer in Egypt, and you play it as it is. We keep developing it, so the rules and numbers may change from one release to the next.` },
  { h: 'The two currencies', p: '“Happy New Year” ([[كل سنة وانت طيب]]) is the match currency and it ends with the match. Lahlouh ([[لحلوح]]) is a permanent balance that you spend in the shop. Neither has any cash value, neither can be turned into money, and neither can be sold or bought outside the game.' },
  { h: 'Real-money purchases', p: 'You can buy Lahlouh or “Make your character” from the shop inside the game. Payment is made through the Apple or Google store and under their terms, and the price is shown before you confirm. Lahlouh is stored on your device with a copy on our server, and comes back with the recovery code if you change your device. It does not come back if you delete your account. “Restore purchases” restores “Make your character” only. A refund is requested from Apple or Google under their terms, and this does not affect any right you have under the law of your country. If you are under 18, buy with the permission of your parent or guardian.' },
  { h: 'Rooms', p: 'Whoever creates the room chooses its settings. Any player can leave the match at any time with the “Exit the match” ([[اطلع من الماتش]]) button, and an unfinished match earns no points. The server does not check every gameplay move.' },
  { h: 'Before online play', p: 'Your name is shown to everyone in the room. Names and behaviour that include swearing, insults or harassment are forbidden. When you enter online play and press “Agree”, you agree to these terms.' },
  { h: 'Respect', p: 'Do not choose a name or do anything that includes swearing, insults, harassment or impersonating someone. You can block any player: you will not see their messages or emojis, and we will not put you with them in quick play. And you can report them with the “Report” button. We review reports within 24 hours, and we may change an offensive name or ban the reported device from online play. If many players from different rooms report the same person, their name or online play is locked automatically for a day until we review it.' },
  { h: 'Game rights', p: 'The game, its characters, cards, artwork and texts belong to the project owner or are used with the permission of their owners, and are available for personal play only. Copying, republishing or selling them is forbidden.' },
  { h: 'Real people', p: 'Some characters (those carrying the “based on a real person” stamp) are based on real people who agreed to it. The artwork is a caricature, for fun, and not a true description of them. Most of the game’s artwork and some of its sounds were made with artificial-intelligence tools. The Instagram button on a character opens that person’s account outside the game, and the other Instagram buttons open the game’s page. If any of them withdraws consent, we will remove the character in the nearest update, and if you had bought it, we will give you its price back in Lahlouh.' },
  { h: 'No warranty', p: 'To the extent the law allows, there is no guarantee that the game will run without faults or that your account will not be lost: we keep a second copy so that we can restore it, but we do not guarantee it. This does not cancel any right you have as a consumer under the law of your country. These terms are governed by Egyptian law. If we change these terms, we will write the change here with its date, and if it is big we will tell you inside the game.' },
  { h: 'Contact', p: `The person responsible for your data is ${NAME}, an individual developer in Egypt. For any question or request about your data, email hello@maslahagame.com. The game’s Instagram page, maslaha_game, is for news only, not for data requests.` },
]

// Site-only addition (coordinator decision 2): the landing page's own analytics. Arabic and English say the same thing.
export const SITE_AR = {
  h: 'الموقع',
  id: 'site',
  p: 'صفحة اللعبة على الإنترنت بتعدّ الزيارات بخدمة PostHog (سيرفراتها في فرانكفورت بألمانيا، جوه الاتحاد الأوروبي) من غير كوكيز ومن غير ما نخزّن عنوان النت بتاعك. بنسجّل بس الصفحة اللي فتحتها والأزرار اللي ضغطت عليها ونوع جهازك والموقع اللي جيت منه، ومفيش أسماء ولا إيميلات. ولما الصفحة تسأل سيرفر اللعبة عن عدد اللي بيلعبوا دلوقتي، السيرفر بيشوف عنوان النت بتاعك زي أي اتصال. وبنحترم إعداد «عدم التتبع» في متصفحك.',
}
export const SITE_EN = {
  h: 'This website',
  id: 'site',
  p: 'The game’s web page counts visits with PostHog (its servers are in Frankfurt, Germany, inside the European Union) without cookies and without storing your IP address. We only record which page you opened, which buttons you pressed, your device type and the site you came from, and no names or emails. When the page asks the game server how many people are playing right now, the server sees your IP address, like any connection. We respect the “Do Not Track” setting in your browser.',
}
